version: '3.1'
services:
  db:
    container_name: MariaDB
    image: mariadb
    restart: always
    # default: 3306:3306
    ports:
      - ${HOST_PORT}:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
volumes:
  data:
  config: